<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VLNacionalidadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nacionalidades = [
            ['abreviatura' => 'AFG', 'nombre' => 'Afganistan'],
            ['abreviatura' => 'ALB', 'nombre' => 'Albania'],
            ['abreviatura' => 'ALG', 'nombre' => 'Algeria'],
            ['abreviatura' => 'AND', 'nombre' => 'Andorra'],
            ['abreviatura' => 'ANG', 'nombre' => 'Angola'],
            ['abreviatura' => 'AGU', 'nombre' => 'Anguilla'],
            ['abreviatura' => 'ANT', 'nombre' => 'Antigua'],
            ['abreviatura' => 'AHO', 'nombre' => 'Antillas, Holandesas'],
            ['abreviatura' => 'ARG', 'nombre' => 'Argentina'],
            ['abreviatura' => 'ARM', 'nombre' => 'Armenia'],
            ['abreviatura' => 'ARU', 'nombre' => 'Aruba'],
            ['abreviatura' => 'AUS', 'nombre' => 'Australia'],
            ['abreviatura' => 'AUT', 'nombre' => 'Austria'],
            ['abreviatura' => 'AZE', 'nombre' => 'Azerbaijan'],
            ['abreviatura' => 'BAH', 'nombre' => 'Bahamas'],
            ['abreviatura' => 'BRN', 'nombre' => 'Barhain'],
            ['abreviatura' => 'BAN', 'nombre' => 'Bangladesh'],
            ['abreviatura' => 'BAR', 'nombre' => 'Barbados'],
            ['abreviatura' => 'BLR', 'nombre' => 'Bielorusia'],
            ['abreviatura' => 'BEL', 'nombre' => 'Belgica'],
            ['abreviatura' => 'BIZ', 'nombre' => 'Belice'],
            ['abreviatura' => 'BEN', 'nombre' => 'Benin'],
            ['abreviatura' => 'BER', 'nombre' => 'Bermuda'],
            ['abreviatura' => 'BHU', 'nombre' => 'Butan'],
            ['abreviatura' => 'BOL', 'nombre' => 'Bolivia'],
            ['abreviatura' => 'BIH', 'nombre' => 'Bosnia Herzegobina'],
            ['abreviatura' => 'BOT', 'nombre' => 'Botswana'],
            ['abreviatura' => 'BRA', 'nombre' => 'Brasil'],
            ['abreviatura' => 'IVB', 'nombre' => 'Islas Vírgenes Británicas'],
            ['abreviatura' => 'BRU', 'nombre' => 'Brunei'],
            ['abreviatura' => 'BUL', 'nombre' => 'Bulgaria'],
            ['abreviatura' => 'BUR', 'nombre' => 'Burkina Faso'],
            ['abreviatura' => 'BDI', 'nombre' => 'Burundi'],
            ['abreviatura' => 'CMR', 'nombre' => 'Camerun'],
            ['abreviatura' => 'CAN', 'nombre' => 'Canada'],
            ['abreviatura' => 'CPV', 'nombre' => 'Cabo Verde'],
            ['abreviatura' => 'CAY', 'nombre' => 'Islas Caimán'],
            ['abreviatura' => 'CAF', 'nombre' => 'Cent. African R.'],
            ['abreviatura' => 'CHA', 'nombre' => 'Chad'],
            ['abreviatura' => 'CHI', 'nombre' => 'Chile'],
            ['abreviatura' => 'CHN', 'nombre' => 'China, P.R.'],
            ['abreviatura' => 'TPE', 'nombre' => 'Chinese Taipei'],
            ['abreviatura' => 'COL', 'nombre' => 'Colombia'],
            ['abreviatura' => 'COM', 'nombre' => 'Comoros'],
            ['abreviatura' => 'CGO', 'nombre' => 'Congo'],
            ['abreviatura' => 'COK', 'nombre' => 'Islas Cook'],
            ['abreviatura' => 'CRC', 'nombre' => 'Costa Rica'],
            ['abreviatura' => 'CIV', 'nombre' => 'Costa de Marfil'],
            ['abreviatura' => 'CRO', 'nombre' => 'Croacia'],
            ['abreviatura' => 'CUB', 'nombre' => 'Cuba'],
            ['abreviatura' => 'CYP', 'nombre' => 'Chipre'],
            ['abreviatura' => 'CZE', 'nombre' => 'Rep. Checa'],
            ['abreviatura' => 'DEN', 'nombre' => 'Dinamarca'],
            ['abreviatura' => 'DJI', 'nombre' => 'Djibuti'],
            ['abreviatura' => 'DMA', 'nombre' => 'Dominica'],
            ['abreviatura' => 'DOM', 'nombre' => 'República Dominicana'],
            ['abreviatura' => 'ECU', 'nombre' => 'Ecuador'],
            ['abreviatura' => 'EGY', 'nombre' => 'Egipto'],
            ['abreviatura' => 'ESA', 'nombre' => 'El Salvador'],
            ['abreviatura' => 'ENG', 'nombre' => 'Inglaterra'],
            ['abreviatura' => 'GEQ', 'nombre' => 'Guinea Ecutorial'],
            ['abreviatura' => 'EST', 'nombre' => 'Estonia'],
            ['abreviatura' => 'ETH', 'nombre' => 'Etiopía'],
            ['abreviatura' => 'MKD', 'nombre' => 'Macedonia'],
            ['abreviatura' => 'FER', 'nombre' => 'Islas Feroe'],
            ['abreviatura' => 'FIJ', 'nombre' => 'Fiji'],
            ['abreviatura' => 'FIN', 'nombre' => 'Finlandia'],
            ['abreviatura' => 'FRA', 'nombre' => 'Francia'],
            ['abreviatura' => 'PLY', 'nombre' => 'F. Polinesia'],
            ['abreviatura' => 'GAB', 'nombre' => 'Gabon'],
            ['abreviatura' => 'GAM', 'nombre' => 'Gambia'],
            ['abreviatura' => 'GEO', 'nombre' => 'Georgia'],
            ['abreviatura' => 'GER', 'nombre' => 'Alemania'],
            ['abreviatura' => 'GHA', 'nombre' => 'Gana'],
            ['abreviatura' => 'GIB', 'nombre' => 'Gibraltar'],
            ['abreviatura' => 'GRE', 'nombre' => 'Grecia'],
            ['abreviatura' => 'GRN', 'nombre' => 'Granada'],
            ['abreviatura' => 'GDP', 'nombre' => 'Guadalupe'],
            ['abreviatura' => 'GUM', 'nombre' => 'Guam'],
            ['abreviatura' => 'GUA', 'nombre' => 'Guatemala'],
            ['abreviatura' => 'GUI', 'nombre' => 'Guinea'],
            ['abreviatura' => 'GBU', 'nombre' => 'Guinea-Bissau'],
            ['abreviatura' => 'GUY', 'nombre' => 'Guyana'],
            ['abreviatura' => 'HAI', 'nombre' => 'Haiti'],
            ['abreviatura' => 'HON', 'nombre' => 'Honduras'],
            ['abreviatura' => 'HKG', 'nombre' => 'Hong Kong'],
            ['abreviatura' => 'HUN', 'nombre' => 'Hungría'],
            ['abreviatura' => 'ISL', 'nombre' => 'Islandia'],
            ['abreviatura' => 'IND', 'nombre' => 'India'],
            ['abreviatura' => 'INA', 'nombre' => 'Indonesia'],
            ['abreviatura' => 'IRQ', 'nombre' => 'Irak'],
            ['abreviatura' => 'IRI', 'nombre' => 'Irán'],
            ['abreviatura' => 'IRL', 'nombre' => 'Irlanda (Eire)'],
            ['abreviatura' => 'NIR', 'nombre' => 'Irlanda del norte'],
            ['abreviatura' => 'ISR', 'nombre' => 'Israel'],
            ['abreviatura' => 'ITA', 'nombre' => 'Italia'],
            ['abreviatura' => 'JAM', 'nombre' => 'Jamaica'],
            ['abreviatura' => 'JPN', 'nombre' => 'Japon'],
            ['abreviatura' => 'JOR', 'nombre' => 'Jordania'],
            ['abreviatura' => 'KAM', 'nombre' => 'Kampuchea'],
            ['abreviatura' => 'KAZ', 'nombre' => 'Kazakhstan'],
            ['abreviatura' => 'KEN', 'nombre' => 'Kenia'],
            ['abreviatura' => 'KOR', 'nombre' => 'Corea'],
            ['abreviatura' => 'PRK', 'nombre' => 'Corea, PDK'],
            ['abreviatura' => 'KUW', 'nombre' => 'Kuwait'],
            ['abreviatura' => 'KGZ', 'nombre' => 'Kyrghyzstan'],
            ['abreviatura' => 'LAO', 'nombre' => 'Laos, D.P.R.'],
            ['abreviatura' => 'LAT', 'nombre' => 'Latvia'],
            ['abreviatura' => 'LIB', 'nombre' => 'Líbano'],
            ['abreviatura' => 'LES', 'nombre' => 'Lesotho'],
            ['abreviatura' => 'LBR', 'nombre' => 'Liberia'],
            ['abreviatura' => 'LBA', 'nombre' => 'Libyan Arab J.'],
            ['abreviatura' => 'LIE', 'nombre' => 'Liechtenstein'],
            ['abreviatura' => 'LTU', 'nombre' => 'Lituania'],
            ['abreviatura' => 'LUX', 'nombre' => 'Luxemburgo'],
            ['abreviatura' => 'MAC', 'nombre' => 'Macao'],
            ['abreviatura' => 'MAD', 'nombre' => 'Madagascar'],
            ['abreviatura' => 'MAW', 'nombre' => 'Malawi'],
            ['abreviatura' => 'MAS', 'nombre' => 'Malasia'],
            ['abreviatura' => 'MDV', 'nombre' => 'Islas Maldiva'],
            ['abreviatura' => 'MLI', 'nombre' => 'Mali'],
            ['abreviatura' => 'MLT', 'nombre' => 'Malta'],
            ['abreviatura' => 'MSH', 'nombre' => 'Islas Marshall'],
            ['abreviatura' => 'MQE', 'nombre' => 'Martinica'],
            ['abreviatura' => 'MTN', 'nombre' => 'Mauritania'],
            ['abreviatura' => 'MRI', 'nombre' => 'Mauritius'],
            ['abreviatura' => 'MEX', 'nombre' => 'Mejico'],
            ['abreviatura' => 'MLD', 'nombre' => 'Moldova'],
            ['abreviatura' => 'MON', 'nombre' => 'Mónaco'],
            ['abreviatura' => 'MGL', 'nombre' => 'Mongolia'],
            ['abreviatura' => 'MTS', 'nombre' => 'Montserrat'],
            ['abreviatura' => 'MAR', 'nombre' => 'Moroco'],
            ['abreviatura' => 'MOZ', 'nombre' => 'Mozambique'],
            ['abreviatura' => 'MYA', 'nombre' => 'Myanmar'],
            ['abreviatura' => 'NAM', 'nombre' => 'Namibia'],
            ['abreviatura' => 'NEP', 'nombre' => 'Nepal'],
            ['abreviatura' => 'NED', 'nombre' => 'Holanda'],
            ['abreviatura' => 'NZL', 'nombre' => 'Nueva Zelanda'],
            ['abreviatura' => 'NCA', 'nombre' => 'Nicaragua'],
            ['abreviatura' => 'NIG', 'nombre' => 'Nigeria'],
            ['abreviatura' => 'NOR', 'nombre' => 'Noruega'],
            ['abreviatura' => 'OMA', 'nombre' => 'Oman'],
            ['abreviatura' => 'PAK', 'nombre' => 'Pakistan'],
            ['abreviatura' => 'PLE', 'nombre' => 'Palestina'],
            ['abreviatura' => 'PAN', 'nombre' => 'Panamá'],
            ['abreviatura' => 'PNG', 'nombre' => 'Papúa Nueva Guinea'],
            ['abreviatura' => 'PAR', 'nombre' => 'Paraguay'],
            ['abreviatura' => 'PER', 'nombre' => 'Perú'],
            ['abreviatura' => 'PHI', 'nombre' => 'Filipinas'],
            ['abreviatura' => 'POL', 'nombre' => 'Polonia'],
            ['abreviatura' => 'POR', 'nombre' => 'Portugal'],
            ['abreviatura' => 'PUR', 'nombre' => 'Puerto Rico'],
            ['abreviatura' => 'QAT', 'nombre' => 'Qatar'],
            ['abreviatura' => 'ROM', 'nombre' => 'Rumania'],
            ['abreviatura' => 'RUS', 'nombre' => 'Russia'],
            ['abreviatura' => 'RWA', 'nombre' => 'Ruanda'],
            ['abreviatura' => 'SAI', 'nombre' => 'Saipan'],
            ['abreviatura' => 'ASA', 'nombre' => 'Samoa Americana'],
            ['abreviatura' => 'SAM', 'nombre' => 'Samoa'],
            ['abreviatura' => 'SMR', 'nombre' => 'San Marino'],
            ['abreviatura' => 'STP', 'nombre' => 'S.Tomé & Princ.'],
            ['abreviatura' => 'KSA', 'nombre' => 'Arabia Saudita'],
            ['abreviatura' => 'SCO', 'nombre' => 'Escocia'],
            ['abreviatura' => 'SEN', 'nombre' => 'Senegal'],
            ['abreviatura' => 'SEY', 'nombre' => 'Seychelles'],
            ['abreviatura' => 'SLE', 'nombre' => 'Sierra Leona'],
            ['abreviatura' => 'SIN', 'nombre' => 'Singapore'],
            ['abreviatura' => 'SVK', 'nombre' => 'Eslovakia'],
            ['abreviatura' => 'SLO', 'nombre' => 'Slovenia'],
            ['abreviatura' => 'SOL', 'nombre' => 'Islas Salomón.'],
            ['abreviatura' => 'SOM', 'nombre' => 'Somalía'],
            ['abreviatura' => 'RSA', 'nombre' => 'Sudáfrica'],
            ['abreviatura' => 'ESP', 'nombre' => 'España'],
            ['abreviatura' => 'SRI', 'nombre' => 'Sri Lanka'],
            ['abreviatura' => 'SKN', 'nombre' => 'St. Kitts'],
            ['abreviatura' => 'LCA', 'nombre' => 'St. Lucia'],
            ['abreviatura' => 'VIN', 'nombre' => 'S.Vincent'],
            ['abreviatura' => 'SUD', 'nombre' => 'Sudán'],
            ['abreviatura' => 'SUR', 'nombre' => 'Surinam'],
            ['abreviatura' => 'SWZ', 'nombre' => 'Suazilandia'],
            ['abreviatura' => 'SWE', 'nombre' => 'Suecia'],
            ['abreviatura' => 'SUI', 'nombre' => 'Suiza'],
            ['abreviatura' => 'SYR', 'nombre' => 'Siria'],
            ['abreviatura' => 'TJK', 'nombre' => 'Tadjikistan'],
            ['abreviatura' => 'TAN', 'nombre' => 'Tanzania'],
            ['abreviatura' => 'THA', 'nombre' => 'Tailandia'],
            ['abreviatura' => 'TOG', 'nombre' => 'Togo'],
            ['abreviatura' => 'TGA', 'nombre' => 'Tonga'],
            ['abreviatura' => 'TRI', 'nombre' => 'Trinidad/Tobago'],
            ['abreviatura' => 'TUN', 'nombre' => 'Tunisia'],
            ['abreviatura' => 'TUR', 'nombre' => 'Turquía'],
            ['abreviatura' => 'TKM', 'nombre' => 'Turkmenistan'],
            ['abreviatura' => 'TUV', 'nombre' => 'Tuvalu'],
            ['abreviatura' => 'UGA', 'nombre' => 'Uganda'],
            ['abreviatura' => 'UKR', 'nombre' => 'Ucrania'],
            ['abreviatura' => 'UAE', 'nombre' => 'Emiratos Arabes Unidos'],
            ['abreviatura' => 'USA', 'nombre' => 'Estados Unidos'],
            ['abreviatura' => 'URU', 'nombre' => 'Uruguay'],
            ['abreviatura' => 'UZB', 'nombre' => 'Uzbekistan'],
            ['abreviatura' => 'VAN', 'nombre' => 'Vanuatu'],
            ['abreviatura' => 'VEN', 'nombre' => 'Venezuela'],
            ['abreviatura' => 'VIE', 'nombre' => 'Vietnam'],
            ['abreviatura' => 'ISV', 'nombre' => 'Islas Vírgenes'],
            ['abreviatura' => 'WAL', 'nombre' => 'Gales'],
            ['abreviatura' => 'YEM', 'nombre' => 'Yemen'],
            ['abreviatura' => 'YUG', 'nombre' => 'Yugoeslavia'],
            ['abreviatura' => 'ZAI', 'nombre' => 'Zaire'],
            ['abreviatura' => 'ZAM', 'nombre' => 'Zambia'],
            ['abreviatura' => 'ZIM', 'nombre' => 'Zimbaue'],
        ];

        DB::table('vl_nacionalidades')->insert($nacionalidades);
    }
}
